[package]
name = "httpz"
description = "todo"
version = "0.1.0"
edition = "2021"

[features]
default = ["axum"] # TODO: Set this to empty
axum = ["dep:axum", "dep:axum-core"]
actix-web = ["dep:actix-web"]
poem = ["dep:poem"]
rocket = ["dep:rocket"]
warp = ["dep:warp"]

[dependencies]
# Webservers
actix-web = { version = "4.1.0", optional = true, features = [] }
axum = { version = "0.5.13", optional = true, features = [] }
axum-core = { version = "0.2.7", optional = true, features = [] }
poem = { version = "1.3.36", optional = true, features = [] }
rocket = { version = "0.5.0-rc.2", optional = true, features = [] }
warp = { version = "0.3.2", optional = true, features = [] }

# Core
cookie = { version = "0.16.0", features = ["percent-encode"] }
http = { version = "0.2.8", features = [] }

[dev-dependencies]
tokio = { version = "1.20.1", features = ["macros"] }
axum = { version = "0.5.13", features = [] }
tower = { version = "0.4.13", features = [] }
hyper = { version = "0.14.20", features = [] }
