[package]
name = "demo"
edition = "2021"
version = "0.0.0"
publish = false

[dependencies]
httpz = { path = "../../../../../", features = ["lambda"] }
tokio = "1.27.0"
lambda_http = "0.7.3"
tracing-subscriber = "0.3.16"
tracing = "0.1.37"
