[package]
name = "demo"
edition = "2021"
version = "0.0.0"
publish = false

[dependencies]
httpz = { path = "../../../../../", features = ["lambda"] }
tokio = "1.21.2"
lambda_http = "0.6.1"
tracing-subscriber = "0.3.15"
tracing = "0.1.36"